theme="amp"
title = "Satish Yadav"
baseurl = "https://github.com/iSatishYadav/amp"
canonifyurls = true
publishDir = "docs"

[params]
    description = "I turn Coffee into Code"

[social]
    twitter = "monstersatish"
    github = "iSatishYadav"
    facebook = "yadavsatish"
